// <auto-generated />
using Domen;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Domen.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20210326175626_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DobavljacProizvod", b =>
                {
                    b.Property<long>("DobavljaciId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProizvodiId")
                        .HasColumnType("bigint");

                    b.HasKey("DobavljaciId", "ProizvodiId");

                    b.HasIndex("ProizvodiId");

                    b.ToTable("DobavljacProizvod");
                });

            modelBuilder.Entity("Domen.Dobavljac", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Napomena")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PIB")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Dobavljac");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Napomena = "Isporuka svakog prvog u mesecu.",
                            Naziv = "Maxi",
                            PIB = "11223344"
                        },
                        new
                        {
                            Id = 2L,
                            Naziv = "Dobavljac DOO",
                            PIB = "9874512"
                        },
                        new
                        {
                            Id = 3L,
                            Naziv = "Bio Spajz",
                            PIB = "9745123"
                        });
                });

            modelBuilder.Entity("Domen.JedinicaMere", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("JedinicaMere");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Naziv = "Komad"
                        },
                        new
                        {
                            Id = 2L,
                            Naziv = "Kilogram"
                        },
                        new
                        {
                            Id = 3L,
                            Naziv = "Litar"
                        },
                        new
                        {
                            Id = 4L,
                            Naziv = "Gram"
                        });
                });

            modelBuilder.Entity("Domen.Proizvod", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Cena")
                        .HasColumnType("float");

                    b.Property<long>("JedinicaMereId")
                        .HasColumnType("bigint");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Pdv")
                        .HasColumnType("float");

                    b.Property<long>("TipProizvodaId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("JedinicaMereId");

                    b.HasIndex("TipProizvodaId");

                    b.ToTable("Proizvod");
                });

            modelBuilder.Entity("Domen.TipProizvoda", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipProizvoda");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Naziv = "Mlecni proizvod"
                        },
                        new
                        {
                            Id = 2L,
                            Naziv = "Slatkis"
                        },
                        new
                        {
                            Id = 3L,
                            Naziv = "Delikates"
                        },
                        new
                        {
                            Id = 4L,
                            Naziv = "Pice"
                        });
                });

            modelBuilder.Entity("DobavljacProizvod", b =>
                {
                    b.HasOne("Domen.Dobavljac", null)
                        .WithMany()
                        .HasForeignKey("DobavljaciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domen.Proizvod", null)
                        .WithMany()
                        .HasForeignKey("ProizvodiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domen.Proizvod", b =>
                {
                    b.HasOne("Domen.JedinicaMere", "JedinicaMere")
                        .WithMany()
                        .HasForeignKey("JedinicaMereId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domen.TipProizvoda", "TipProizvoda")
                        .WithMany()
                        .HasForeignKey("TipProizvodaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JedinicaMere");

                    b.Navigation("TipProizvoda");
                });
#pragma warning restore 612, 618
        }
    }
}
